### ISSUE TITLE
MCPPPP

### ISSUE THREAD

**Issue by Rajbir98** [Fabulously-Optimized/fabulously-optimized#106]
### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/mcpppp

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/mcpppp

### Source/other link

https://github.com/supsm/MCPPPP

### Mod file size

2.49 MiB

### What it does

A mod which converts from optifine/mcpatcher format to other formats

### Why should it be in the modpack

It is maintained and more efficient than LambdAurora/MCPatcherPatcher #73 And more recommended by FabricSkyboxes

### Why shouldn't it be in the modpack

~~Still Not In CF~~, Can Crash If Using Old Versions Of Resource Packs

Madis0: "the issue with the mod is that it can probably cause your game to hang for a while if you have large zipped resource packs" as stated by the author

### Categories

Works like Optifine/Bedrock Edition/Forge/etc, Replaces an existing mod Request

### Additional details

There's also a Standalone version too
https://github.com/supsm/MCPPPP/releases
Use This Mod With Resource Pack Which Is Updated To The Latest Version Of Minecraft Not Older Than 1.13 Or It May Crash

Madis0: it is approved for CF, but not yet recommended to include by the author
Madis0 edit 2: now on CF, added link above

**Comment by Rajbir98** [comment]
The Modrinth link Is the Jar version which converts Packs In-Game

**Comment by Madis0** [comment]
Interesting. Does it convert the packs automatically though?

**Comment by Rajbir98** [comment]
Yes

**Comment by Rajbir98** [comment]
I have added an issue in https://github.com/supsm/MCPPPP/issues/6 about releasing the mod for CF

**Comment by Rajbir98** [comment]
It Sometimes fails to convert old 1.8.9 Packs
but still, it's Better Than  LambdAurora/MCPatcherPatcher at least MCPPPP Converts The Pack Properly Old One Just Doesn't Convert Properly

**Comment by Rajbir98** [comment]
I recommend using Up-To-date packs

**Comment by Rajbir98** [comment]
I Use The Standalone version Because I also Play with an old resource pack and I have also tried to place a new up-to-date pack and see if it converts it or not surprisingly it converts very well, but you have to be careful before using an old pack it will not make your game crash, but it will crash and let the game start normally

**Comment by Rajbir98** [comment]
Old Pack Means Older than 1.13

**Comment by Rajbir98** [comment]
1.13 works but not older than some, 1.12 versions also work

**Comment by Rajbir98** [comment]
i have edited

**Comment by nchristopher** [comment]
IMO this shouldn't be included in the modpack - users can just run the standalone version once to convert their resources packs. Including this mod wouldn't have any benefit beyond converting packs that one time.

**Comment by Madis0** [comment]
Well, the benefit is being able to run Optifine-based packs as-is, which is a big priority for the modpack.
However the current implementation of MCPPPP is slow (as stated by the author) so I would rather prefer mods that are able to run Optifine format directly.

**Comment by supsm** [comment]
I personally wouldn't recommend adding it yet, since it may cause a lot of waiting while it checks for files to convert in large zipped resourcepacks

> more efficient than LambdAurora/MCPatcherPatcher

This isn't actually necessarily true, especially for the mod version. MCPP only converts what is available during resource reload, whereas MCPPPP converts everything when minecraft is launched. It will unzip and look for things to convert, which may take a while in larger zipped resource packs, as mentioned above.

I plan on using minecraft resource loader to convert the packs in the future, which should make it a bit faster.
I will also add it to curseforge if you want me to.

For the time being, it may be better to add a link to [MCPPPP](http://github.com/supsm/mcpppp) in the readme or curseforge page.

**Comment by supsm** [comment]
Oh... I really haven't updated this in a while have I?  
It's been a pretty long time now since zip resourcepack checking has become fast (released 3 months ago). Now, checking resourcepacks should take less than half a second. With that said, there are a few other new issues that should be taken into consideration:
- Does not work on macOS <11 due to standard library changes. It won't crash, just refuse to convert 
- conversion and unzipping process will still slow down startup. When there is nothing to convert, however, the startup time should barely be impacted.
- hashing folders with many items may take some time (usually up to 5 seconds)
- no in-game config or anything
  
At this point, I would no longer say that is isn't recommended to use the mod version, but ultimately it is up to you to weigh the pros and cons and make the decision. I hope I've provided enough info for this, please let me know if you need to know more details.

**Comment by Madis0** [comment]
Thanks for the insight @supsm. Will see if the mods and current tradeoffs are worth it.

**Comment by Madis0** [comment]
Rejected due to the inclusion of #505.
