### ISSUE TITLE
Add essential

### ISSUE THREAD

**Issue by Maximusbarcz** [Fabulously-Optimized/fabulously-optimized#166]
### Mod name

Essential

### Curseforge link

Non-existing 

### Other links

essential.gg

### What it does

Its mainly libary mod but it also adds few qol fetures, in-game account switcher, friending in-game, most vanilla feel cosmetics and many more 

### Why should it be in the modpack

The friending is very nice same as the (some free) cosmetics and just all the things in it 

### Why shouldn't it be in the modpack

Well it doesn’t add “that” much and adds some things into the pause gui some people may not like, also its not on curseforge and you need to (i think) to partner with then

### Categories

New feature

**Comment by Madis0** [comment]
Hmm, interesting idea.

* I've confirmed it is allowed in CF modpacks, though I don't expect it to ever be on CF itself, so every update would slow down FO releases by up to 3 days (as with Modrinth-only mods).
* Doesn't feel like it is a fast mod to update to new versions of the game, especially because it doesn't exist on 1.13-1.16.
* Doesn't feel like it will always stay on Fabric (or even Quilt), it may just be a temporary stopgap until Forge reaches feature parity or whatever.
* Ecosystem lock-in. Regarding previous two points, it does lock down the users to Minecraft or FO versions that have the mod, there is no way to create compatible alternatives to this mod (unlike with capes for example, which could be expanded to support even more services and have several alternative mods in case the current one dies).

The answer right now is a no.

**Comment by user859347** [comment]
The mod is also available on CurseForge: https://www.curseforge.com/minecraft/mc-mods/essential-mod

**Comment by Madis0** [comment]
Cool, but right now I'm leaning towards the ecosystem point. Maybe if there was an open-source, smaller alternative mod for this...
