### ISSUE TITLE
Client side note blocks

### ISSUE THREAD

**Issue by guio75t855t** [Fabulously-Optimized/fabulously-optimized#201]
### Mod name

Client side note blocks

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/client-side-noteblocks

### Other links

https://github.com/DaCubeKing/ClientSideNoteblocks
https://modrinth.com/mod/clientsidenoteblocks

### What it does

Reduces lag from playing noteblocks

### Why should it be in the modpack

No noteblock lag

### Why shouldn't it be in the modpack

Not many people use noteblocks

### Categories

Performance optimization

**Comment by Madis0** [comment]
> Why isn't this mod working on X server?
> This mod will not work on some servers that use a protocol hack because this mod requires the proper block data to be sent to the client. 

There is no use for this mod if it doesn't work on every server anyway... Most popular Java Edition servers use some kind of protocol tweaking. 

Also, I don't really like
>  It also filters out [...] the sounds that you get from breaking a block.
because that breaks vanilla behaviour.

**Comment by DaCubeKing** [comment]
I'm the creator of the mod and I'd like to help clarify a few things.

> There is no use for this mod if it doesn't work on every server anyway... Most popular Java Edition servers use some kind of protocol tweaking.

I've actually not played on any server that has caused issues with this mod. I only really put that in because there because I suspected that there might be a tiny number of servers that would have issues. 

Any 1.13+ server should work fine with no issues and any 1.8+ server with viaversion on the actual server (not proxy) should also work fine. I would only expect issues to arise if a pre-1.13 server is using viaversion on the proxy or if the player is using a mod (like multiconnect) to connect to a pre-1.13 server. Additionally, viaversion really isn't used on the proxy afaik (At least on the servers I've been on) due to other issues that you get with that setup.

> It also filters out [...] the sounds that you get from breaking a block.

It only does that for noteblocks in case that wasn't clear.
#
Regardless of that, this mod was made for a really specific usecase that I suspect most players won't benefit from. It *only* affects behavior when you left click a noteblock to play it. It does not affect noteblocks played by redstone or the tuning of noteblocks. It should, though, be invisible during normal gameplay.

**Comment by Madis0** [comment]
Thank you for the write-up, @DaCubeKing!

The mod is still rejected per this paragraph: 
>  It only affects behavior when you left click a noteblock to play it. It does not affect noteblocks played by redstone or the tuning of noteblocks.
