### ISSUE TITLE
RebindAllTheKeys

### ISSUE THREAD

**Issue by terabyte25** [Fabulously-Optimized/fabulously-optimized#206]
### Mod name

RebindAllTheKeys

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/rebindallthekeys

### Other links

https://modrinth.com/mod/rebind-all-the-keys

### What it does

RebindAllTheKeys allows for other keys such as the debug screen (F3) and narrator keys to be reminded to any key. 

### Why should it be in the modpack

Allows for more fine-tuned keybinds on user-side, potential reduces annoying instances of enabling the narrator on accident.

### Why shouldn't it be in the modpack

While it supports 1.18 currently, it seems to be updated and maintained somewhat sparsely for new versions.

### Categories

New feature

**Comment by Madis0** [comment]
Those keys are for debug options though, why should a normal user need to rebind them?

> potential reduces annoying instances of enabling the narrator on accident.

Ehh, I've had this happen, but that was also because I bound something to B myself. This would not happen in the default setup and seems unlikely that users would bind vanilla keys to that as well (unless using non-QWERTY layouts).

To sum this up: convince me that this mod is not niche.

**Comment by Madis0** [comment]
Debug keys are not meant to be changed by most (normal) users, any changes make it harder to give support as well.

**Comment by isXander** [comment]
I use a 65% keyboard which makes using debug keys a pain.
