### ISSUE TITLE
Incomprehensibly large .logs

### ISSUE THREAD

**Issue by Claymeister** [Fabulously-Optimized/fabulously-optimized#224]
### Describe the bug

So I've been cleaning my files, and noticed that my MultiMC instances weigh a ton.
It's not a problem with the modpack itself, but i have no idea which specific mod might cause the logs to be massive.
I had to download Vim to open the massive files even.

### Expected behavior

The logs not to weigh in excess of megabytes

### Observed/actual behavior

They did. Every microsecond or so ( there are like thousands logs every second) a problem with OpenGL is logged
[evidence1.txt](https://github.com/Fabulously-Optimized/fabulously-optimized/files/7835713/evidence1.txt)
[ev2.txt](https://github.com/Fabulously-Optimized/fabulously-optimized/files/7835714/ev2.txt)
.

### Steps To Reproduce

sry i have no idea where else to put the evidence

### Modpack version

Sry but not modpack

### Launcher

MultiMC

### Install method

Using with additional mods/something else (please write below)

### Additional context

simply, the more i played the bigger the files got. after like 20 mins there is a 600 mb latest.log
they get compressed to a thousand fold size decrease tho
![obraz](https://user-images.githubusercontent.com/97406383/148696910-24cb3b98-cc0d-4529-bd55-fec2b9cffa97.png)

**Comment by Madis0** [comment]
Please send me the logs to pastebin or equivalent.

**Comment by Madis0** [comment]
Sorry, I didn't notice you already sent logs. The issue is very likely caused by the shaders you are using. Here are my suggestions:

- Make sure you are using the latest version of FO, which has the latest Iris - that may already fix it
- If you want shaders, I suggest you to pick some from here: https://github.com/IrisShaders/Iris/blob/trunk/docs/supportedshaders.md
- Try running it without shaders as well
- Update your graphics drivers if possible

**Comment by DioEgizio** [comment]
1. Have you an overlay like overwolf? Remove it, they have issues with Minecraft
