### ISSUE TITLE
Distant Horizons Crash

### ISSUE THREAD

**Issue by WitherSkell** [Fabulously-Optimized/fabulously-optimized#298]
### Describe the bug

i disabled NotEnoughCrashed and Farseek just to be sure
with them the same happen
[latest.log](https://github.com/Fabulously-Optimized/fabulously-optimized/files/8531986/latest.log
[2022-04-21-7.log.gz](https://github.com/Fabulously-Optimized/fabulously-optimized/files/8531992/2022-04-21-7.log.gz)
)

also first issue

### Modpack version

the newest (1.18.2)

### Launcher

GDLauncher

### Other things

- [ ] I updated FO to a newer version (mention, what version to what version)
- [X] I removed or added some mods (mention, which ones)

**Comment by Poopooracoocoo** [comment]
Just for future reference please don't say "the newest" when asked for your version. And because you checked the box that you have added or removed mods from Fabulously Optimized, please specify which mods. Cheers.

I was able to reproduce the error with Fabulously Optimized 3.5.0 for Minecraft 1.18.2 and [Distant Horizons 1.6.2 for 1.18.1](https://www.curseforge.com/minecraft/mc-mods/distant-horizons/files/3651470). Removing FarSight did not resolve the issues.

The CurseForge description says the following:
>The version support numbers are strict!
>If a version says it supports MC 1.18.1 it will NOT work on 1.18.2!

**Comment by Poopooracoocoo** [comment]
@WitherSkell ICYMI Distant Horizons is now available for 1.18.2 in [alpha 1.6.3](https://www.curseforge.com/minecraft/mc-mods/distant-horizons/files/3764444)
