### ISSUE TITLE
Cape Editor website

### ISSUE THREAD

**Issue by RaptaG** [Fabulously-Optimized/fabulously-optimized#346]
Since [OptiFine has a cape editor](https://optifine.net/capeChange) for user-selected colors, I think FO should have one too!

**Comment by Madis0** [comment]
I don't get your question. FO doesn't host capes and the tutorial to get one is already in the wiki[is already in the wiki](https://fabulously-optimized.gitbook.io/modpack/readme/free-cape) ...

**Comment by RaptaG** [comment]
> I don't get your question. FO doesn't host capes and the tutorial to get one is already in the wiki..

I meant a website where you would be able to change the colors of the text and the background color of the cape, like the [MinecraftCapes' OF cape editor](https://minecraftcapes.net/gallery/optifine-capes).

**Comment by Madis0** [comment]
Right. 
Well, I've never seen anyone with a FO cape besides myself, so I don't think there is much interest in this. Especially because users can use any image they want 😛

If you want, you could find an online image tool that can take an url and change the image's hue (colors) and write a tutorial about it in the wiki.
