### ISSUE TITLE
1.19 optional mods are outdated and don't work

### ISSUE THREAD

**Issue by ASOwnerYT** [Fabulously-Optimized/fabulously-optimized#368]
### Describe the bug

There is a feature in ATLauncher (and probably other launchers) where you can select optional mods to add as well as the required mods. In the 1.19 alpha, when you select any of the optional mods they don't work because they are for 1.18 and don't support 1.19.

For example, the file [Packwiz/1.19/mods/lambdabettergrass.pw.toml](https://github.com/Fabulously-Optimized/fabulously-optimized/blob/main/Packwiz/1.19/mods/lambdabettergrass.pw.toml) is in the 1.19 folder and has `optional` set to `true`. But this mod is for 1.18, not 1.19, so it causes the game to crash on launch.

### Modpack version

4.0.0-alpha.5

### Launcher

MultiMC

### Other things

- [X] I updated FO to a newer version (mention, what version to what version)
- [ ] I removed or added some mods (mention, which ones)

**Comment by Madis0** [comment]
This is known, and it's mainly because I'm lazy and want to make the alpha updates fast for you and easy for me (by keeping it in the list instead of re-adding).

I have considered removing those if I get a lot of reports, but for now - it's alpha anyway, deal with it 😄

I don't support ATLauncher yet, but this also affects MultiMC (auto-update) so might as well keep it open for now.

**Comment by Madis0** [comment]
Aah, got hit by #364 again as it wasn't yet fixed by CurseForge 🙄 
I guess at this point I will just move those mods to a local folder to keep track, haha.
