### ISSUE TITLE
No Chat Reports / Mojang Chat Reporting meta 

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#376]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/no-chat-reports

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/no-chat-reports

### Source/other link

https://github.com/Aizistral-Studios/No-Chat-Reports

### What it does

Enables chat signing only on servers that require it, reverts annoying visual changes to chat, shows the current state of the server 

### Why should it be in the modpack

See https://github.com/Fabulously-Optimized/fabulously-optimized/issues/376#issuecomment-1200153322 and [chat reporting FAQ](https://fabulously-optimized.gitbook.io/modpack/readme/chat-reporting-faq)

### Why shouldn't it be in the modpack

Chat status icons are not fully accurate (mostly yellow on 1.19.1)

Also see https://github.com/Fabulously-Optimized/fabulously-optimized/issues/376#issuecomment-1200153322

### Categories

Fixes a bug/makes another mod work

### Additional details

**Comment by Madis0** [comment]
So apparently this is not as easy as installing a mod and everything is fixed. 

Quoting the mod description (which was updated later): 

> To make Velocity compatible with this mod, add `-Dauth.forceSecureProfiles=false` to your Java command line flags (on the server side, when starting Velocity). 

Velocity is a popular proxy system for PaperMC, a popular server platform.

Interesting note about PaperMC itself though, emphasis mine:

> Minecraft 1.19 introduced client-side signing of chat messages, allowing other clients to verify a message has been sent by the player, delivered verbatim and unmodified by the server. In the future, the client will most likely visually distinguish signed player messages, unsigned player messages, and system messages. Because we want to avoid issues with upstream compatibility and duplicate work, we are not yet able to provide an API for that system. **Currently, all messages will be sent as (unsigned and unverified) system messages – this has no meaningful impact on how clients display these messages yet.** With Mojang trying to make the player chat more secure, we will have to make some larger additions and changes around message events and API in the future to allow features like the ability to preview formatted messages on the client.

https://forums.papermc.io/threads/paper-1-19.344/

**Comment by TheCoder3156** [comment]
I would like to point out that it isn't clear if adding `-Dauth.forceSecureProfiles=false` to the velocity cmd args is required to make velocity work depending if the mod is used server side or velocity just won't let you join if you use it client side. The poster of that doesn't give a source and I can't find reference of it anywhere else.

**Comment by Madis0** [comment]
https://www.minecraft.net/en-us/article/minecraft-1-19-1-release-candidate-1

>
* The “Profanity”, “Nudity or pornography” and “Extreme violence or gore” categories have been removed
* The description for the “Drugs and alcohol” category has been updated to “Someone is encouraging others to partake in illegal drug related activities or encouraging underage drinking”
* The description of the “Harassment and bullying” category has been extended with the following: or posting private personal information about you or someone else without consent (“doxing”).
* Increased the amount of chat context sent with each chat report

**Comment by fredster33** [comment]
This should be removed. Reports remove users that are not welcome in the Minecraft community, sometimes committing real-life crimes (doxxing is illegal in Hong Kong, terrorism is illegal worldwide, illegal drugs are prohibited, etc). This update shifts responsibility for obvious violations of clear, common sense bad activity to Microsoft instead of server admins, allowing them to focus on other activities. This mod would allow those people to thrive, bullying and harassing people without recourse.

**Comment by Madis0** [comment]
@fredster33 
Here are some issues I have with the report system. For more context, see the videos I've linked in the readme disclaimers.

* **Sent to Microsoft instead of server admins** - this system would be amazing if the reports were sent to server admins, it could create a truly consistent and smooth way of reporting players in all servers. But sending the reports to the wrong entity does inheritly mean a different judgment of the reported cases. And different outcomes too - admins may not even know they should ban a person from their community spaces (like forums) because they were just not notified of it.

* **Report categories that do not match the server rules** - despite removing some categories, there are still things that servers may want to or may not want to enforce that are missing/added to those rules here. For example, if there is an adult-only server that may discuss things like alcohol freely, but when an underage player stumbles upon it, they can report others for things that are clearly allowed and intended by the server.

* **Lack of context** - few lines of server chat are a lot less context than player builds, signs, Discord/forum general behavior etc. Only server admins have the full context. 
Also, take the rule "impersonation". How can you be sure a person is who they claim to be with few lines of chat? Are you going to do a background search on them, based on their Microsoft profile? _(shudders)_ Are you just going to assume they lie and ban them? At that point you can not even say who you are in any way because you can get banned either way.

* **No concept of appeals at all** - mistakes happen even by the best of us and the help articles describe no concept of appeals to any bans. The fact that _some_ bans are temporary is not really the solution as an unjust ban is an unjust ban. This issue has already been prevalent in Bedrock Edition.

* **Bots and mass reporting** - there is still no wording on how would they solve the issue of bots and mass unjust reporting. Okay, blocking multiple reports from a single account are easy... (Or are they? Imagine being a lawful citizen who joined an anarchy server where 10+ users do already break the Community Guidelines. Who will get banned, you for reporting or them for actually breaking the rules?) but what about an x amount of players reporting an user they don't like for a message that is taken out of context? That could happen to, for example, YouTube celebrities, long-time players of a server or people with rare capes.

**Comment by fredster33** [comment]
* Sent to Microsoft - I believe I refuted this point. Again. *reports remove users that are not welcome in the Minecraft community* - these users would be ushered out in *every* server. This system takes the burden off of server admins.
* Report categories - See above. Adult content servers do not belong on Minecraft, as was stated many times in the past by Microsoft.
* Lack of context - Microsoft can see other data such as profile data and user activity. If they do not have full context, they would lean towards not taking action rather than doing so, and again, **this does not remove the chance for server admins themself to ban - if they have more context, they can do so.**
* Appeals - Wording will be added. This, again, has not been rolled out fully - it is still in a preview stage.
* Bots - Microsoft has anti-bot measures already within Minecraft. Microsoft can see context, so that argument is false. 
I'd like to add that most of your arguments fall under a false dilemma fallacy - you are picking out portions of the system that can be removed or changed, as it has not been rolled out yet (but heck, Minecraft can be updated even if a feature went in stable) but assuming that it's a black-and-white, include or not include situation.

**Comment by Madis0** [comment]
> Sent to Microsoft - I believe I refuted this point. Again. _reports remove users that are not welcome in the Minecraft community_ - these users would be ushered out in _every_ server. This system takes the burden off of server admins.

Okay, let's assume Microsoft does really want to help the server admins. Why do the admins not get a say in this then? By making it opt-out, adding an API to get notified of Microsoft-induced punishments, letting /unban override Microsoft's decidion and so on.

> Report categories - See above. Adult content servers do not belong on Minecraft, as was stated many times in the past by Microsoft.

Having played in both child-friendly and adult-friendly servers, I do not agree, they both serve a different niche. If there is a need for a rating system to determine the audience of a server, sure, why not, but banning all adult servers is not acceptable. I've also heard an unverified claim that the average age of a Java Edition player is higher compared to Bedrock Edition, it was 24 if I recall correctly.

> Lack of context - Microsoft can see other data such as profile data and user activity. If they do not have full context, they would lean towards not taking action rather than doing so, and again, **this does not remove the chance for server admins themself to ban - if they have more context, they can do so.**

What profile data and user activity? If a player says "I'll kill you" that is meant for game context or subtly discusses alcohol without knowing the other player's age, it is a lack of context. Admins can indeed ban by themselves but they can not override Microsoft's ban, which is the problem.

> Appeals - Wording will be added. This, again, has not been rolled out fully - it is still in a preview stage.

It is not in a preview stage for Bedrock though, which already has those issues - [vague reasons and many people do not even know about appeals.](https://youtu.be/kEfyaAq90kg?t=110)

> Bots - Microsoft has anti-bot measures already within Minecraft. Microsoft can see context, so that argument is false.

Fair enough, bots themselves may not be that big of an issue. But it has already [been proven that important context can be faked or removed](https://www.youtube.com/watch?v=JVpfqXxMke0), and Microsoft cannot do anything about that if they simply do not receive it.

>   I'd like to add that most of your arguments fall under a false dilemma fallacy - you are picking out portions of the system that can be removed or changed, as it has not been rolled out yet (but heck, Minecraft can be updated even if a feature went in stable) but assuming that it's a black-and-white, include or not include situation.

It is a case of being rather safe than sorry due to the vagueness and widespread enforcement of the system, plus any existing information we already know about the way it works on Bedrock Edition.

I am concerned about my own account, I am concerned about others' accounts. If the player breaks the server's rules or breaks the law, it is understandable that they should be punished. But this system seems to be technically and ethically very inadequate right now (trusting the client and assuming the context of a few message lines too much). 

Should they rethink the entire system (besides just removing a report category or two), I would gladly remove that mod.

**Comment by fredster33** [comment]
Your Bedrock claim is also irrelevant - this is a Java modpack.

**Comment by Julienraptor01** [comment]
> Your Bedrock claim is also irrelevant - this is a Java modpack.
> 

What do you mean by that ? Microsoft try to make the same as possible so what apply to one will likely apply to the other.

**Comment by RaptaG** [comment]
1.19.1 is officially released

**Comment by aurorasmiles** [comment]
I'd like to add a bit of context:

> But it has already [been proven that important context can be faked or removed](https://www.youtube.com/watch?v=JVpfqXxMke0), and Microsoft cannot do anything about that if they simply do not receive it.

The issue you linked in that video has been patched before release. There is a new similar variant of this, which is not really an actual concern. See also https://gist.github.com/kennytv/ed783dd244ca0321bbd882c347892874?permalink_comment_id=4248479#gistcomment-4248479 and 
![grafik](https://user-images.githubusercontent.com/21148213/181709068-114c3155-5d8d-44ad-aada-d614b928a49c.png)

> plus any existing information we already know about the way it works on Bedrock Edition.

> Microsoft try to make the same as possible so what apply to one will likely apply to the other.

While there is a strive for general version parity, you need to remember that Bedrock has a very different playerbase, system, distribution as Java. Bedrock needs to follow very strict rules, especially in the App Store, that might require chat filtering. A chat filtering system on Java wouldn't be trivial to implement, and extremly easy to remove. This is not a valid concern for Java at the moment (it is horrible, but not on Java)

On the server I work on I have `enforce-secure-profiles` enabled, and so far everyone (less than 5 users) that tried to join with this mod installed had this mod from this modpack, didn't know it was in here, and immediately removed it after I explained it to them. I don't see any reason why a modpack that mostly focuses on optimization needs a mod like this included. The people that don't want it can always install it (or a better alternative that doesn't just rip out signatures), but most people that use this modpack don't care IMO.
I'd suggest removing it now, waiting a few more weeks now that 1.19.1 is released, and see if any horror stories come true (unlikely), after that you can always add it back in

**Comment by Julienraptor01** [comment]
> I'd like to add a bit of context:
> 
> > But it has already [been proven that important context can be faked or removed](https://www.youtube.com/watch?v=JVpfqXxMke0), and Microsoft cannot do anything about that if they simply do not receive it.
> 
> The issue you linked in that video has been patched before release. There is a new similar variant of this, which is not really an actual concern. See also https://gist.github.com/kennytv/ed783dd244ca0321bbd882c347892874?permalink_comment_id=4248479#gistcomment-4248479 and 
> ![grafik](https://user-images.githubusercontent.com/21148213/181709068-114c3155-5d8d-44ad-aada-d614b928a49c.png)
> 
> > plus any existing information we already know about the way it works on Bedrock Edition.
> 
> > Microsoft try to make the same as possible so what apply to one will likely apply to the other.
> 
> While there is a strive for general version parity, you need to remember that Bedrock has a very different playerbase, system, distribution as Java. Bedrock needs to follow very strict rules, especially in the App Store, that might require chat filtering. A chat filtering system on Java wouldn't be trivial to implement, and extremly easy to remove. This is not a valid concern for Java at the moment (it is horrible, but not on Java)
> 
> On the server I work on I have `enforce-secure-profiles` enabled, and so far everyone (less than 5 users) that tried to join with this mod installed had this mod from this modpack, didn't know it was in here, and immediately removed it after I explained it to them. I don't see any reason why a modpack that mostly focuses on optimization needs a mod like this included. The people that don't want it can always install it (or a better alternative that doesn't just rip out signatures), but most people that use this modpack don't care IMO.
> I'd suggest removing it now, waiting a few more weeks now that 1.19.1 is released, and see if any horror stories come true (unlikely), after that you can always add it back in
> 

Yes but there is now another way
https://youtu.be/ipkFCrbB3Cg

**Comment by aurorasmiles** [comment]
> There is a new similar variant of this, which is not really an actual concern. See also https://gist.github.com/kennytv/ed783dd244ca0321bbd882c347892874?permalink_comment_id=4248479#gistcomment-4248479

please also read the entire messsage and not just parts of it^^

**Comment by Madis0** [comment]
@aurorasmiles 
Thank you for the feedback, I'll delve into that graph later.

I have also made a 1.19.1 FAQ which has more details and counterpoints, forgot to post it here. https://fabulously-optimized.gitbook.io/modpack/readme/1-19-1-faq

I understand that the system may have good goals, but the way they implemented and communicated this still seems highly unethical, so I am still really concerned. Even the latest snapshot posts' changelogs omitted several important changes around the system.

If they want us to trust the system, why not be transparent about it? Why is that graph not made and released by Mojang, but instead a third party?

> I don't see any reason why a modpack that mostly focuses on optimization needs a mod like this included.

FO has also been combatting unwanted changes from vanilla and mods for a long time, this is one.

**Comment by Madis0** [comment]
I've now read the entire gist and comments of Kenny and posted some detailed comments there to ask for more clarification.

Meanwhile I've decided to clarify some reasons why NCR benefits FO:

Pros

* Replaces _(technically adds, but FO disables the original as it is not very helpful)_ the vanilla multiplayer warning with a server-based one, that shows up only where relevant and explains the user what is exactly going on, so they can make their own decision upon it.
* Shows a status icon with a descriptive tooltip above chat textbox
* Hides the chat bars and symbols that users don't really need to know or care about. In FO's sense, I'd say only the yellow icon is useful (messages that server hid or modified) so I'll re-enable it soon
* Hides the technically accurate, but for most users uninformative and annoying toast when joining servers that don't enforce signatures.
* By default, hides the report button on servers that take measures against reporting anyway. In FO I've currently set it to hide the button on all servers to discourage the use of the feature (why is detailed in the FAQ).
* Protects users from currently known and later found signing-related exploits where possible
* Protects users from getting reported by others where possible (why is detailed in the FAQ).

Cons

* Users see scary warnings on servers that show no warnings at all in vanilla.
   * Ignorance is bliss? But seriously, all NCR is doing here is being clear to the user what is going on so they can make an informed decision. That is also something many users suggested Mojang to do, but look - they added the opposite, a vague toast for servers that don't have signing.
* Other users will see red bars and icons in chat by a FO user if the server allows unsigned messages. 
   * The solution to that is for the server to either use plugins that modify messages to remove those or to enforce signing altogether. I don't see a reason why the client should willingly send signatures to potentially put themselves at risk where it is not required.
* Users may still want to report others, this is disabled for all servers in FO. 
   * I could re-enable it if the reason is argumented, but the idea is to not get users used to that vague reporting system and instead prefer server admins or other means (chat hiding, local police, suicide prevention resources). I still don't see how Mojang could make a better decision for, say, "impersonation", compared to the server admins.
* Users may still want to see the toast or chat bars/symbols. 
   * These can be re-enabled in config or re-enabled by FO if argumented. I don't see why most users would need them though, especially because the system was initially planned to be introduced without those and I could find no feedback from users who would request to see such things - this is very technical information that is needed only for mod/plugin debugging or while creating a chat report.

**Comment by nrgill28** [comment]
While I disagree with the inclusion of NCR in FO by default, I would at least suggest changing the text found on the curseforge page / other platform pages to make it more clear about its inclusion. 

Currently the curseforge page has text at the top in a normal font size reading:
> 1.19.1 beta is on the sidebar. [Read the 1.19.1 FAQ.](https://www.curseforge.com/linkout?remoteUrl=https%253a%252f%252ffabulously-optimized.gitbook.io%252fmodpack%252freadme%252f1-19-1-faq)

My suggestion would be to change this to something more along the lines of:
> Fabulously Optimized 1.19.1 beta contains the No Chat Reports mod by default. [Read the 1.19.1 FAQ.](https://www.curseforge.com/linkout?remoteUrl=https%253a%252f%252ffabulously-optimized.gitbook.io%252fmodpack%252freadme%252f1-19-1-faq)

**Comment by Madis0** [comment]
@nrgill28 

Thank you for the idea, I've rephrased it as:
> FO does not include chat reporting on Minecraft 1.19.1. Read the FAQ.

I don't want to promote a specific mod or movement. I want to make users aware of what this feature entails and make a "safe" default decision based on its technical approach and ethics. Users can continue to join servers that enforce signing, just unlike vanilla they will be clearly informed of the risks.

If you have more constructive criticism, please share. I'm interested in various viewpoints to minimize my own bias towards this.

_P.S. Regardless of whether chat reporting is enabled or not in FO, I would still find a mod to hide all the visual annoyances added since 1.19.1-pre2 because these just confuse the user anyway, as I wrote in my previous comment here._

**Comment by nrgill28** [comment]
I do also want to go over some of what is mentioned in the FAQ and give my opinion on them as well, as I think parts of it are misleading or inaccurate.

## Why is it bad?
### Banned from all multiplayer
>  instead of getting punished on one server, you are getting punished on all, including Realms and others' LAN servers. Maybe you just got angry on one server and want to go to another to relax again? Nope, cannot do that.

I think what bugs me with this one is how it implies you can get a ban by just 'being angry'. From [Mojang's FAQ](https://help.minecraft.net/hc/en-us/articles/7317376541197-Minecraft-Java-Edition-Player-Reporting-FAQ) they say that

> The type of behavior that will get you banned is hate speech, bullying, harassing, sexual solicitation, or threatening others.

So if you got 'angry' enough to yell slurs at someone, harass them, or similar, then yes I agree that a ban in that instance would be deserved. But you aren't going to get a ban by telling someone to 'fuck off' or other normal things which I would consider 'being angry'.

### Realms subscriptions don't get cancelled
>  if you get banned, Mojang will not automatically cancel any Realms servers you own, meaning you'll continue to pay for server(s) you cannot access or control.

If you get a temporary ban, this makes sense. Most people who have realms have them to play with friends, you wouldn't want your world inaccessible to them just because you can't join it for some period of time. Permanent ban on the other hand, yes then your realm should get cancelled. Regardless of which ban you receive, I am unsure if you retain the capability to manage your realm to download the world or similar, which would be the point I would make here if you are not able to.

### Report reviewers lack context
> players can select 1-4 messages, to which the system will add up to 7 messages before and 2 after the selected ones - at most 40 messages in total. That is a very partial context as it is missing player builds, signs, books, Discord/forum messages, daily general behavior etc.

I think there's a general misunderstanding of the types of messages that Mojang intends to act on when it comes to chat reporting, people are hyper focused on this small section between what is clearly OK and what will clearly get you a ban. The types of messages that I believe Mojang will act on do not need more context than what is being sent them. Stuff like "I hate all [slurs]", or "I'll pay you $50 if you send me nudes". It's these clear-cut cases that I believe they're going for, stuff which is beyond a reasonable doubt, rather than pandering over the details of someone replying 'yes' to a message not intended for them baiting them into agreeing to something they don't.

### Fairness doesn't scale
> Minecraft has a huge playerbase and if lots of players play it, lots can report each other as well. How can Mojang guarantee a fair action to be done on thousands of reports every day? Compare that to a single server that has less players, therefore less reports and less admins needed.

Again same as above. I believe they will primarily be acting on clear-cut cases where it's easy to show beyond a reasonable doubt that the player said something terrible. I do however think they should be more public about what kinds of infractions will get you which kind of punishment, and how those punishments scale with repeat infractions.

### Categories don't match server rules
> for example, if there is an adult-only server that may discuss things like alcohol freely, but when an underage player stumbles upon it, they can report others for things that are clearly allowed and intended by the server.

I cannot find an updated list for the reasons you can report someone, but from Mojang's FAQ they no longer mention drugs / alcohol as a bannable offense. However the stuff that they do say you will be banned for are things that you will _very likely_ get banned by the server for anyway.

### Categories, ban reasons, appeals are vague
> for example, take the rule "impersonation". How can one be sure a person is who they claim to be with just a few lines of chat? Are they just going to assume it is a lie and ban them? At that point players can not even say who they are because they can get banned either way.

I think this is more meant for someone using a server plugin to change their name to that of a popular figure, to then take advantage of that to exploit others. You won't get banned for just claiming that you're Dream, you will get banned for claiming that and then asking for someone's credit card number, the expiry date, and the three digits on the back.

> While there is a way to appeal, it is not described when and how many times it will be accepted. The fact that some bans are temporary is not really the solution - an unjust ban is an unjust ban. This issue has already been prevalent in Bedrock Edition

The linked video here raises a good point, and I agree that it's not ideal to not be told the exact specifics of how you got banned (say by providing the reported messages), but it's a double edged sword. If you get told which message got you banned, you can then reasonably figure out who reported you and go after them further. 

On the topic of receiving unjust bans that's something we'll just have to wait and see about. I don't believe it's fair to speculate in this instance as Mojang say they have a whole special team dedicated to this. In any case, we will find out in the coming months. Additionally, if you receive multiple 'unjust bans' perhaps they were not unjust...? Either that or you're being targeted by someone or a group of people, which should be fairly easy for Mojang to detect and deal with.

### Unfixed exploits
I do not believe there's any significant unfixed exploits remaining in the final release of 1.19.1. This part should be removed as it only serves to fearmonger anyone reading the FAQ, especially as it provided no sources for these claims.

There is the [issue mentioned in kennytv's thread](https://gist.github.com/kennytv/ed783dd244ca0321bbd882c347892874?permalink_comment_id=4250256#gistcomment-4250256) and I agree with all of what kennytv has said in response to that.

## Final notes
I don't think the chat report system is perfect. It can definitely be improved still, especially in the areas of more clearly communicating to the players what they will and won't get banned for, and how you might have gotten banned. However I don't think it's bad either, and I honestly believe that in a few months time all of this will have blown over.

For the average player who might use this modpack, I believe it will confuse them more if No Chat Reports is included by default, especially later down the line when the drama has died down. The average player will not have their account 'at risk' _just_ from sending signed chat messages, they also have to say something genuinely terrible to risk a ban.

**Comment by Madis0** [comment]
@nrgill28 

> Banned from all multiplayer

Well, "hate speech" _is_ a vague concept and people know of various ways to insult others, that doesn't even have to include any threats. It is also possible for humans to act completely differently in different situations.

> Realms subscriptions don't get cancelled

Well, according to what we know, players don't get access to the Realms menu at all. So it is only a matter of how much can they do from off-game (e.g. minecraft.net) and I don't think there are any world download or other basic server toggles there, only entire subscription perhaps.

> Report reviewers lack context

So far these are just assumptions and faith. We don't know if it's always just "clear-cut" cases because there are still limits to what is being sent.

> Fairness doesn't scale

Yes, they should be more public about the actions taken. Either way there are a lot of players out there, and reports should be resolved fast, so...

> Categories don't match server rules

Here is the list of reasons and it does include "drugs or alcohol": https://help.minecraft.net/hc/en-us/articles/7149823936781-Player-Reporting-in-Minecraft-Java-Edition

> I think this is more meant for someone using a server plugin to change their name to that of a popular figure, to then take advantage of that to exploit others. You won't get banned for just claiming that you're Dream, you will get banned for claiming that and then asking for someone's credit card number, the expiry date, and the three digits on the back.

Well, it doesn't say anywhere that it would be that; renaming theirselves while having signed messages should be impossible; and that reason should fall onto a different category anyway.

> The linked video here raises a good point, and I agree that it's not ideal to not be told the exact specifics of how you got banned (say by providing the reported messages), but it's a double edged sword. If you get told which message got you banned, you can then reasonably figure out who reported you and go after them further.

I wouldn't expect to see the individual messages, but just a crystal-clear reason sentence. That video proved that this is already an issue in Bedrock, so there is less faith for it to be better on Java, it is the same overall game after all. 

> I do not believe there's any significant unfixed exploits remaining in the final release of 1.19.1. This part should be removed as it only serves to fearmonger anyone reading the FAQ, especially as it provided no sources for these claims.

That one I agree with, as it becomes incredible _because_ I don't provide sources.

> However I don't think it's bad either, and I honestly believe that in a few months time all of this will have blown over.

I also believe it will blow over, not because it becomes any more insignificant, but rather because players will adapt. Similar to 1.8/1.9+ case - some will not upgrade, some will ignore, some will work around.

---

Overall, while I didn't agree with most of your points (as evident above), you've convinced me to compromise a bit.

I will soon re-enable the report button (to give the option back on servers that allow it) and disable the warning screen of No Chat Reports (warning fatigue; most users would probably accept anyway). 
That means NCR will continue to work only on servers where signing is not required and users will still have a consistent and transparent way of seeing the status, unlike vanilla's vague icons and warnings.

Might also change the FAQ wording a bit once I think about it more.

Reg. your edit: I posted the link you wanted above and I still don't agree with at least "hate speech", "impersonation/false information" and "drugs or alcohol" because the intent is harder to determine for those.

**Comment by nrgill28** [comment]
Ah, there is an article describing all the reasons. Good to know. They have at least 3 articles on the topic now and it's definitely confusing, thanks for linking that.

> renaming theirselves while having signed messages should be impossible;

It is not impossible. Chat signatures are based entirely on your UUID, not your username. Plugins to change your username will still work and will still show valid signatures. But yes it is a very specific example that I thought of.

I admit that a big reason I am on the other side of this fence is because I have no reason to distrust Mojang just yet; giving innocent players false bans is obviously not in their interest. One thing I must criticize Mojang on here is their poor communication of the feature from the start, which absolutely contributed to this whole ordeal. All we have to go from is our interpretations of less than ideal articles and statements, drawing our own conclusions. We won't know for sure what all this means until it settles down. Until then, I guess we wait.

**Comment by Madis0** [comment]
Recent changes:

* FO finally updated to 1.19.2 (blame CurseForge for the delay); 1.19 and 1.19.1 are unsupported
* The listing stance has been changed to:
   * > FO *discourages* chat reporting on Minecraft 1.19.1+.
* Chat reporting FAQ received a few new points and changes, notably:
   * Whether NCR is a risk
   * Stance on exploits
   * Benefits of NCR if you like the reporting system
* As of 4.2.0-beta.1, the full-screen server warning has been disabled, people can continue to see the status via the icon near the chatbox
   * If there will be more exploits that don't get promptly fixed, I might have to re-enable it for some time, but I hope not

I will continue to observe the situation as it evolves, meanwhile here is a good technical video to watch: https://youtu.be/DobmW1ZUcbQ
