### ISSUE TITLE
Simple Voice Chat

### ISSUE THREAD

**Issue by Carterpersall** [Fabulously-Optimized/fabulously-optimized#386]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat

### CurseForge Mod Distribution

Allowed

### Source/other link

https://github.com/henkelmax/simple-voice-chat

### What it does

Adds voice chat support into minecraft. Requires server-side mod as well as the client-side mod.

### Why should it be in the modpack

Many people use this mod to communicate with others on public and private servers. I don't think it would do any harm to add it as the mod doesn't do anything if there is no server-side mod installed. To hide the icons, you could add `hide_icons` to the config file as shown at https://modrepo.de/minecraft/voicechat/wiki?t=configuration

### Why shouldn't it be in the modpack

It shows an icon on the bottom left of the screen when the server doesn't have the mod installed. This can be averted though by adding the previously stated config option.

### Categories

New feature

**Comment by Madis0** [comment]
* One of the main principles of the modpack is that all features should work in all servers, especially because I provide no server packs at all. This breaks that.
* I recently used this mod in a server and I found it annoying (others expect you to have sound) and disorienting (the icons were not always consistently displayed, so I didn't know who was talking)
* Many servers use Discord already for that purpose.
