### ISSUE TITLE
Recursive Resources 

### ISSUE THREAD

**Issue by RaptaG** [Fabulously-Optimized/fabulously-optimized#468]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/recursive-resources

### CurseForge Mod Distribution

Allowed

### Modrinth link

Not approved yet

### Source/other link

https://github.com/enjarai/recursive-resources

### Mod file size

34.8 KB

### License

MPL-2.0 (Open Source)

### What it does

Enhances the resource pack menu

### Why should it be in the modpack

Vanilla like QoL mod

### Why shouldn't it be in the modpack

Does it fit in FO?

### Additional details

There's no other mod doing that for Fabric 1.19+

**Comment by Julienraptor01** [comment]
I can understand how it could be nice especially for the search feature but the folder thing seems a bit cursed.
Can you enable a whole folder at once or is it for "organize" only ?
I put organize in quote because, yes the menu can be messy very fast in vanilla if you have many RP but having things in subfolder if you don't have a perfect organisation complicate the thing.
And as complement, if things are in folders, is the search recursive ?
What does the search search, only the name or also the description ?
What is the purpose of having folders when you can search if it's not recursive ? (this is a question only if it's not recusive, i'm not saying it isn't recursive, just asking)

**Comment by RaptaG** [comment]
> I can understand how it could be nice especially for the search feature but the folder thing seems a bit cursed. [...]

Ask here: https://github.com/enjarai/recursive-resources/issues

:)

**Comment by RaptaG** [comment]
> Can you enable a whole folder at once or is it for "organize" only?

No

> And as complement, if things are in folders, is the search recursive?
What does the search search, only the name or also the description?

It searches both name and description

> What is the purpose of having folders when you can search if it's not recursive?
(this is a question only if it's not recursive, I'm not saying it isn't recursive, just asking)

To keep stuff organized

**Comment by Madis0** [comment]
* Organize resource pack into folders that you can navigate from within the game
   * Err... okay, but what's the benefit? Who has so many resource packs that they need to organize in folders? With worlds or servers I'd understand.
* Choose between folder view (navigate in and out of folders) and flat view (packs from all folders shown in a single list)
   * Aha, so it's for resource packs that are packed improperly and users who are lazy to unpack them 😂
* Search pack names and description (supports the * wildcard)
   * Again, why resource packs of all things?
* Sort packs and folders alphabetically from A-Z or Z-A
   * ^

**Comment by RaptaG** [comment]
:C
