### ISSUE TITLE
No Chat Reports violates a principle of Fabulously Optimized

### ISSUE THREAD

**Issue by cafestifflered** [Fabulously-Optimized/fabulously-optimized#497]
### What config to change

Please change or remove your statement of principles for Fabulously Optimized, which includes this line:

`Neutrality - the modpack should only give you the essential tools and fixes to customize your game, not include any opinionated extras itself (e.g. a mod that adds more environment sounds).`
https://fabulously-optimized.gitbook.io/modpack/readme/principles

It would be acceptable to either remove this section entirely, or to change it to say that your principles are:

`Not Neutrality - the modpack will give you the essential tools and fixes to customize your game, as well as those extra mods that the maintainers deem are valuable to them (e.g. a mod that is controversial but the maintainers like)`

Or remove the No Chat Reports mod from the pack.

### Why should it be changed

The No Chat Reports mod touches a highly controversial and opinionated topic in the Minecraft community. There are many people on all sides of the discussion who have their own opinions on whether chat reporting is a positive or negative. The mod itself has no impact at all on the performance optimization of Minecraft.

It is, therefore, a highly opinionated addition to the modpack and should either be removed, along with the "! Chat Reporting FAQ" page on the documentation website, or that line should be removed from the principles statement, or changed, as it is false.

If you should find yourself upset that I am recommending these changes, consider that this is my opinion, and your emotional reaction to my suggestion is likewise based on your opinion. With so many emotions and opinions being felt around this topic, it makes clear that the principles statement about being non-opinionated must be removed or changed, or the mod removed.

### Additional details

A similar line should be considered for adjustment due to the inclusion of No Chat Reports. By including No Chat Reports by default, you take away autonomy from servers who wish to encourage users to use Fabulously Optimized while also using chat reports as a backup for their own moderation processes if they agree with the chat reporting feature and want to use it.

With No Chat Reports added by default, this principally is arguably false:
`Consistency - Fabulously Optimized must be sustainable, 100% server-compatible`

**Comment by cafestifflered** [comment]
I want to add another comment on why this is important to me. I'm not simply trying to stir-up an argument.

I learned about this modpack from the infamous Michael, and I immediately began using it and recommending it widely. Why? The values, the attention to detail, and the quality of the modpack was high. The principles were important to me and it allowed me to trust the project.

Your principles are why why I didn't suspect it would even have NCR included and why I didn't bother to keep up with the new FAQ page or other changes. I trusted the principles you had established, and I simply updated my pack regularly and encouraged others to do the same. I only learned about the mod's inclusion today when I finally decided to hover over the green checkmark in chat.

Seeing the principle of neutrality be violated by including NCR is what's disappointing to me. I will respect you keeping the mod if you want, even though I'll stop using it, as long as you update your principles to match this decision. It would show integrity and that your convictions and values matter, which was my entire reason for downloading and recommending the pack in the first place.

However, if you keep the mod and keep the "Neutrality" statement as it is, that would not be a respectable decision and I would be really disappointed to see that.

**Comment by Madis0** [comment]
Thank you for the detailed feedback. I understand where you are coming from, but you also seem to be missing a few things.

Here's my response:

* The most important thing to note is that Fabulously Optimized is using a highly customized config for No Chat Reports. That's why, especially due to your lengthy feedback, I highly recommend you to read my [chat reporting FAQ](https://fabulously-optimized.gitbook.io/modpack/readme/chat-reporting-faq) in its entirety, but perhaps most importantly ["I still think chat reporting is fair"](https://fabulously-optimized.gitbook.io/modpack/readme/chat-reporting-faq#i-still-think-chat-reporting-is-fair.).
It is not fair to compare this with the mod's default configuration and as such, the mod's description is changed in-game to reflect it and the modpack's description no longer directly mentions its name.
* While you focus on the principle of Neutrality (more on that later), you seem to be missing the Privacy and Transparency parts. Regardless of what you think of the reporting itself, the mod is here for:
  * Removing the highly misleading chat indicators of 1.19.1, [replacing them with actually explanatory icons](https://fabulously-optimized.gitbook.io/modpack/readme/chat-reporting-faq#what-does-this-modpack-do-to-protect-me), as you noticed (transparency)
     * The users are now actually aware, which servers have chat reporting and what it entails for them (transparency)
     * Except that one rectangle Mojang shortly added to the vanilla launcher, I feel like they do way too little to actually communicate those changes to the user and where they apply. These icons fix that by giving the users information, letting them do their own decidions.
  * The servers can unenforce chat signing (`enforce-secure-profile` in server.properties) and this mod actually lets the clients realize that in practice (privacy)
     * That means servers which don't require it will get less data transmission from the client as well, similar to what FO [has done with telemetry and chat preview](https://fabulously-optimized.gitbook.io/modpack/readme/changed-options) - privacy-first defaults
     * When the servers do force chat signing, [this modpack will work identically to vanilla](https://fabulously-optimized.gitbook.io/modpack/readme/chat-reporting-faq#i-still-think-chat-reporting-is-fair.), which is probably what you were confused about
* Neutrality. I'll admit [I was a lot more opinionated about this at the beginning](https://github.com/Fabulously-Optimized/fabulously-optimized/issues/376), but an user like you brought me down to Earth and as such, the stable version of FO 4.2.0 was released with a config similar to current one, aka minimally intrusive. Maybe you consider the new chat icons opinionated, and you would not necessarily be wrong. However, as I previously mentioned, the icons were enabled in FO _because_ the game itself currently:
  * does not tell, which servers actually have chat reporting
  * does not tell the consequences of getting reported
  * has misleading fearmongering in the icons and toast, the information just isn't correct
  * does not communicate the effects of using Realms, within Realms, at all
       * So in the end it fixes what vanilla didn't - giving the user transparency and privacy-friendly defaults. If you have specific suggestions about the communication here (that feels not "neutral" enough), feel free to let me know.
* [The first snapshot for 1.19.3 includes chat changes](https://www.minecraft.net/en-us/article/minecraft-snapshot-22w42a), including 
  * the removal of chat preview (disabled in FO since the first 1.19 alpha)
  * reduction of scaremongering in chat icons (fixed by NCR and its config in FO)
  * more transparency for deleted and filtered messages (no changes for those in FO right now)
       * Whether all chat changes are for the better, remains to be seen. But it does seem that the situation is improving and in the future NCR may need to change even less about the vanilla chat. 
Whether I remove NCR altogether, depends all on vanilla now. If vanilla will communicate the system's effects better and not force clients to send signatures to servers that don't want it in the first place, NCR might as well not be in FO.
* With all that said, do I think 
   * users need to be aware of No Chat Reports' presence in FO,
   * must they read the FAQ and 
   * does it change their gameplay? 
       * I think I've set it up in the way that the answer is no. The icons look a bit different and the chat looks cleaner but that's about it. Servers that didn't enable chat reporting won't have the clients send the signatures either and servers that do have chat reporting, work exactly like they did in vanilla.

**Comment by cafestifflered** [comment]
I won't be able to address the entire content of your reply at this time, but I'd ask you to consider one thing going back to my purpose of making this post:

I am challenging your claim at neutrality in your principles.

You state that chat reporting uses fear-mongering tactics in its delivery of warning messages and the like. Yet, you shared a link re: "I think chat reporting is fair" where it shows what kind of "help" the mod provides.

It labels servers that have chat reporting enabled with a scary ⚠️ . Hover over that and you can learn that chatting on that server puts you at risk for being permanently globally banned under false-reports. Something that has not yet happened, but continues to be used to terrify players into fearing servers that have it enabled.

This is not "100%" (as your principles say) supported on servers if some of those servers receive hate by encouraging players to use your modpack and then being judged by a ⚠️ icon for having chat reports enabled.

Not only is this fear-mongering itself (just in the direction your opinion believes is right), but, again, it takes away the autonomy of the servers to make their own decisions without judgement from the mod in the form of a warning, or your opinion on the matter (these go against two of your principles).

The details of nearly everything you described are you justifying your decision to include NCR, and yet:

1- It does not optimize performance
2- None of the justification changes that it conflicts with your principles

You can have wonderful, perfect justifications for adding NCR, but fundamentally you are still contradicting your principles by including it. The valuable features you mention in NCR that could be useful for players (and I agree that some would be useful) could also be packaged under a different mod entirely and remove the highly opinionated nature of NCR.

**Comment by Madis0** [comment]
> It labels servers that have chat reporting enabled with a scary ⚠️. Hover over that and you can learn that chatting on that server puts you at risk for being permanently globally banned under false-reports.
>
> A ⚠️ does not mean, "This server has chat reporting enabled so you can feel safer (if you believe chat reporting makes you safer)". That would probably look more like a ✔️ if true. No, the ⚠️ means, "Chat reporting makes you unsafe no matter what you believe, and you should be afraid of this server for having it enabled"
> 
> That's not "help", that's advertising for NCR.

I would bring two analogies to that symbol:

* [Counter-Strike VAC-secured symbol](https://www.tobys.dk/cs/img/vac-server.png) - a symbol that indicates whether a server uses Valve's AntiCheat and therefore if you get banned by that, you get cross-banned from a lot of servers. Since I have not played that game for a long while, nor have I cheated on it, I don't know whether having it is a good or bad thing. All I know is that I am thankful that the icon is there, notifying me of its presence.
* [A video surveillance sign in real life](https://www.discountsafetysigns.co.nz/wp-content/uploads/2017/02/SECURITY_THESE_PREMISES_ARE_PROTECTED_BY_VIDEO_SURVEILLANCE.jpg) - the sign or lack thereof doesn't really indicate whether any wrongdoing will get you caught, how wrongdoing is interpreted, what are the consequences etc. All it says is that you need to be aware that you are recorded when you enter this property.

Same thing in Minecraft. Previously, all servers were under the assumption that everything you do is managed by the server administration. Now, some servers have a new variable - your chat messages may be sent to Mojang and they can affect your chance of playing in all multiplayer servers at once.

This is not "100%" (as your principles say) compatible on servers if some of those servers receive hate by encouraging players to use your modpack and then being judged by a warning icon for having chat reports enabled. Something that harms a server is not compatible with that server.

Not only is this fear-mongering itself (just in the direction your opinion believes is right), but, again, it takes away the autonomy of the servers to make their own decisions without judgement from the mod in the form of a warning, or your opinion on the matter (these go against two of your principles).

> This is not "100%" (as your principles say) compatible on servers if some of those servers receive hate by encouraging players to use your modpack and then being judged by a warning icon for having chat reports enabled. Something that harms a server is not compatible with that server.
> 
> Not only is this fear-mongering itself (just in the direction your opinion believes is right), but, again, it takes away the autonomy of the servers to make their own decisions without judgement from the mod in the form of a warning, or your opinion on the matter (these go against two of your principles).

If you think the current icons are a problem, I can change them. With a bit more effort, I could change the tooltips as well.
But for that, there should be a separate discussion about how should they look and be written as that somewhat goes against your idea that including the whole mod is bad.

> Something that has not yet happened, but continues to be used to terrify players into fearing servers that have it enabled.

[There have](https://www.reddit.com/r/Minecraft/comments/xfh3ee/suspended_from_playing_minecraft_for_swearing_in/) [been bans](https://www.reddit.com/r/Minecraft/comments/x14k5e/minecraft_censoring/). Whether they were rightful or not is up to anyone's guess/interpretation by the provided data.

> The valuable features you mention in NCR that could be useful for players (and I agree that some would be useful) could also be packaged under a different mod entirely and remove the highly opinionated nature of NCR.

Well, that doesn't matter at all. There have been somewhat controversial mods in FO before and as with any big project, there is bound to be some controversy in the future as well. I would even say those people ["can't see the forest for the trees"](https://thecontentauthority.com/blog/what-does-cant-see-the-forest-for-the-trees-mean), with the analogy of a packaged, configured modpack vs individual mods with default options.

> I won't be able to address the entire content of your reply at this time

Well, I'll be waiting for your appendice to this reply then, maybe you'll get a somewhat different perspective from reading my full response.

**Comment by Thanos1716** [comment]
I would also like to add that as Aizistral (NCR dev) has pointed out several times in his various videos on the subject, chat reporting is still in its infancy, so regardless of your stance on whether it is a good thing or not, it is shown to still have various exploits that remain to be addressed by Mojang, I highly recommend watching his [most recent in-depth video](https://www.youtube.com/watch?v=DobmW1ZUcbQ) on why chat reporting is not yet stable, and then consider whether such a feature should have been shipped to the public in its current state. I feel that NCR just gives the players much needed control on an incomplete feature with high stakes, and I feel like that fits with FO privacy and transparency principles quite well.

**Comment by cafestifflered** [comment]
It is clear to me by the latest comments that you will justify your decision using either explanations that have been argued ad-nauseum about chat reporting features, or by brushing off the concerns (ie. Comments like "there will always be something controversial included in a modpack"). So this will be my last comment here.

Your project is using weak principles to manipulate potential users to get them to download your modpack and trust that your decisions are based in neutrality. You are not "Fabulously Optimized", you are "Fabulously Promoting Your Agenda" with regards to No Chat Reports. Whether someone agrees with your explanations for why you include NCR or not, it doesn't change that there is no neutrality in including a mod born out of controversy.

This is, of course, all a matter of opinion. I am disappointed in your decision, but there is no sense in continuing a tired debate steeped in opinion. That very politicially-charged and emotional debate consumed by semantics has been rehashed a thousand times and it won't have any impact on the matter of opinion at the core of this thread, which is that your inclusion of NCR is out of line with your principles.

No matter how you justify your decision and defend your opinion, it doesn't change that simple logical conclusion. If I punch someone, I can explain my reasons for punching them, and they may be fine reasons, but I cannot deny that I punched them. I can no longer say, "I haven't punched anyone".

You can no longer say that you have neutrality and 100% server compatibility as your principles. You can choose to continue to say that if you want, but I don't trust that statement anymore. Of course, that's just my opinion.

Good luck with your project.

**Comment by cafestifflered** [comment]
To be clear: I'm not addressing all of the explanations intentionally. You will not get a full response to all of the points in your reply, and you will not get an "appendice" from me, because my point is those things don't matter to the core of the issue I'm trying to focus on.

I could respond to the details, but that's not the point. I'm not hear to have a battle of attrition and die by a thousand cuts.

**Comment by Madis0** [comment]
So, your core point is still that NCR inclusion opinionated because it changes
![chat_tags](https://user-images.githubusercontent.com/8611110/197227269-75ac7b87-6204-4602-8a1f-3673c50527dd.png)
to
![chat_status_icons_extended](https://user-images.githubusercontent.com/8611110/197227315-8f698f36-5b26-4c40-8256-9079613aa7d9.png)
Again, as I previously mentioned, I understand this, but I just don't currently have a better idea what these icons should be like, in order to be informational, yet neutral.

**Comment by Madis0** [comment]
The conversation has moved to a more actionable issue: https://github.com/Fabulously-Optimized/fabulously-optimized/issues/499
