### ISSUE TITLE
Server resourcepack checker

### ISSUE THREAD

**Issue by ullemini** [Fabulously-Optimized/fabulously-optimized#502]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/server-resourcepack-checker

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/server-resource-pack-checker

### Source/other link

https://github.com/henkelmax/server-resourcepack-checker

### Mod file size

27.92 KB

### License

All Rights Reserved / ARR

### What it does

This client side Fabric mod skips loading server resource packs if the client already has it.

This avoids the annoying Mojang loading bar when joining and leaving servers.

It does this by comparing the file hashes of the resource pack.

### Why should it be in the modpack

Makes it faster to enter servers whit custom resource packs that you already have.

### Why shouldn't it be in the modpack

Its a new ish mod so maybe not tested enough? 
Its also a bit situational because you need to already have the resource pack on  

### Additional details

I found it in Xisuma's Hermitcraft Enhancements mod pack and started to look in to it.

**Comment by Julienraptor01** [comment]
Look interesting but pls don't swear

**Comment by Madis0** [comment]
Interesting indeed, would speed up a lot of games. ARR may be an obstacle at some point, but at the same time it does have proper CF/MR/GH releases.

Only thing I wonder, if it is so easy, why hasn't Mojang done it :joy: Or why isn't it considered a bug?

**Comment by Madis0** [comment]
I misunderstood the mod's purpose.

I thought this would be about _resource pack cache_, e.g. in CubeCraft Lucky Blocks the game needs a resource pack and it is redownloaded every time - I thought the mod would enable it from local cache instead.

Instead, it seems to be about _common_ and _enabled_, like when the server offers you the Faithful pack but there is a chance you have downloaded and enabled it manually anyway.

Therefore, this mod is considered niche and rejected. 

Even if the mod did have the feature I proposed, it would barely be useful because minigame-specific resource packs are really small - for most users the enabling process takes longer than downloading process anyway. Plus, I believe vanilla already has that cache feature, hehe.
