### ISSUE TITLE
Blanket

### ISSUE THREAD

**Issue by GDMgmer3992** [Fabulously-Optimized/fabulously-optimized#555]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/blanket

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/blanket

### Source/other link

https://github.com/BlanketMC/blanket-client-tweaks

### Mod file size

1.07 MB

### License

(any other license)

### What it does

Fix client-side bugs

### Why should it be in the modpack

Fix many client-side bugs, also has some QoL improvements and tweaks And Its Very Configurable

### Why shouldn't it be in the modpack

Untested, Still In Alpha

**Comment by Madis0** [comment]
What specific bugs do you want fixed?

**Comment by Kichura** [comment]
Seems that blanket has bug fixes implemented that mojang already marked as fixed:
[WEB-5587](https://bugs.mojang.com/browse/WEB-5587),
[MC-246465](https://bugs.mojang.com/browse/MC-246465),
[MC-53850](https://bugs.mojang.com/browse/MC-53850)

And the ones that are not resolved:
[MC-238384](https://bugs.mojang.com/browse/MC-238384), 
[MC-187100](https://bugs.mojang.com/browse/MC-187100), 
[MC-175622](https://bugs.mojang.com/browse/MC-175622) 
and [MC-248223](https://bugs.mojang.com/browse/MC-248223).

**Comment by Madis0** [comment]
The fixes I find interesting:

> Fix chat lag on multiplayer servers

That's not the only mod claiming to fix it, but I really fail to see the issue in 1.19.2/1.19.3 so benchmarks are needed for the bugfix and without, if I should care at all.

> Optimized the getBiome call to be 25% - 75% faster

I'm pretty sure that if it really matters, it is already implemented in Sodium/Lithium/etc.

Rejecting this due to the mod not adding anything worthwhile.
