### ISSUE TITLE
ToolTipFix

### ISSUE THREAD

**Issue by Kronosiesium** [Fabulously-Optimized/fabulously-optimized#557]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/tooltipfix

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/tooltipfix

### Source/other link

https://github.com/kyrptonaught/tooltipfix

### Mod file size

12.4 KiB

### License

(any other license)

### What it does

It fixes long tooltips that go off the screen by "folding" the tooltip.

<img width="842" alt="Screenshot 2022-12-30 at 4 38 16 PM" src="https://user-images.githubusercontent.com/96935064/210119872-7115bbf1-625e-4a68-8c90-dfcadb154e0a.png">

### Why should it be in the modpack

It Will help players with really long item names see their items names properly.

### Why shouldn't it be in the modpack

you won't come in contact with it often, and incompatibilities may occur.

**Comment by osfanbuff63** [comment]
We had this mod in for a time (#132), but we removed it for Debugify's fix (#322). However, Mojang "fixed" this issue in 1.19.3 - however we're not sure how well that was executed - so we're evaluating Adaptive Tooltips because Debugify removed the fix (#520).

Going to close this - feel free to submit 1.19.3 testing and things like that in #520 though.
