### ISSUE TITLE
Show Sodium donation button in video settings

### ISSUE THREAD

**Issue by jellysquid3** [Fabulously-Optimized/fabulously-optimized#701]
### What config to change

As it appears [here](https://github.com/Fabulously-Optimized/fabulously-optimized/blob/4b8d6f1e19fe973a0dc7b0074432f5ccbc83150c/Packwiz/1.20.1/config/yosbr/config/sodium-options.json#L1), you are shipping a config file which disables the prompt for a user to consider donating to our project. Please remove this config entry override so that users are shown the prompt again.

### Why should it be changed

This is a single button in the video settings screen and should not bother anyone. If the user is bothered, they can click a single button (right next to our prompt) and permanently dismiss it.

Furthermore, you are the largest modpack on Modrinth and account for many downloads. Likely on top of that, a huge number of users who install your modpack do not understand what Sodium is or that it is significantly responsible for the performance improvement in your modpack. It seems vastly unfair that you should disable our single (non intrusive) message asking for users to donate to our development effort.

**Comment by Madis0** [comment]
**Yes, this was done deliberately and not out of malice.**

The main reason is confusion - who do the donations go to?

* JellySquid alone (remember when you said you were no longer working on Sodium?)
* Sodium developers
* CaffeineMC as a whole
* Sodium Extra/Reese's Sodium Options (because that notably changes the video settings view as well)
* Other mods, who may inject to video settings
* Fabulously Optimized

So... if you can clarify that with the button and the page, we can talk this through, no problem.

---

For other 45 people in this thread, who may think I'm a hater or that I'm taking money away from someone, here are some facts:

* [Fabulously Optimized was created _because of_ Sodium](https://ftb.fandom.com/wiki/Fabulously_Optimized), to popularize it for the mainstream users. I'd say it has succeeded that goal.
* I have contributed to Sodium [with money](https://ko-fi.com/jellysquid_), [with PRs](https://github.com/CaffeineMC/sodium-fabric/pulls?q=is%3Apr+author%3AMadis0+is%3Aclosed) and [other volunteer work](https://github.com/Madis0/sodium-fabric-translations). I do that for most other mods as well.
* I encourage people to choose launchers [that support the modpack and mods](https://github.com/Fabulously-Optimized/fabulously-optimized#downloads). Admittedly, that became more difficult for Sodium since the leaving of CurseForge, but Modrinth App should arrive soon as well.
* [I do not take donations for the modpack itself](https://github.com/Fabulously-Optimized/fabulously-optimized/blob/main/CONTRIBUTING.md). Previously, I suggested users to ["donate to the mods"](https://github.com/Fabulously-Optimized/fabulously-optimized/blob/cdf9916ec089171932971ac8ca4313dabbe05eaa/CONTRIBUTING.md) but for an ever-changing list of mods and unequal amount of donate vs no donate links, I realized that this is biased towards mods that have donation links, despite there also being ways to volunteer (in some way) for others too.

**Comment by FlashyReese** [comment]
> Sodium Extra/Reese's Sodium Options (because that notably changes the video settings view as well)

Just to provide clarity, my mods have never modified the link; the button has merely been relocated for UI enhancements. You can observe the changes [here](https://github.com/FlashyReese/reeses-sodium-options/blame/1.20.x/dev/src/main/java/me/flashyreese/mods/reeses_sodium_options/client/gui/SodiumVideoOptionsScreen.java#L217).

**Comment by intergrav** [comment]
> The main reason is confusion - who do the donations go to?

I've had the donation button enabled in my modpacks ([Additive](https://github.com/intergrav/additive) and [Adrenaline](https://github.com/intergrav/adrenaline)) for a very long time but this issue seems to have never popped up once in my support forum and issue tracker. Granted, FO is far more popular than my stuff but I still personally don't see the issue

**Comment by FlashyReese** [comment]
> > The main reason is confusion - who do the donations go to?
> 
> I've had the donation button enabled in my modpacks ([Additive](https://github.com/intergrav/additive) and [Adrenaline](https://github.com/intergrav/adrenaline)) for a very long time but this issue seems to have never popped up once in my support forum or issue tracker. Granted, FO is far more popular than my stuff but I still personally don't see the issue

I believe they are attempting to raise a distinct concern regarding the ambiguity of the donation button. Not all modpack users may be familiar with Sodium or realize that their donation is directed towards a specific mod. For instance, someone might intend to support all the mods.

**Comment by Kichura** [comment]
Restored.

**Comment by Madis0** [comment]
As Fabulously Optimized prides in its transparency, and because I can still notice some misinformation and misunderstandings regarding this topic, I'd like to publicly address this with a detailed FAQ:

### When did Fabulously Optimized disable this button?

[July 1, 2021 with Fabulously Optimized version 2.0.0b4](https://github.com/Fabulously-Optimized/fabulously-optimized/blob/20d23691e2d2c912d81036f4f3e834a8d7ba6c77/Packwiz/config/yosbr/config/sodium-options.json), and [Sodium (back then - Iris with Sodium) version 0.2.0](https://github.com/CaffeineMC/sodium-fabric/releases/tag/mc1.16.5-0.2.0)

### Why did Fabulously Optimized disable this button?

Because it was unclear, who the donations went to, as described [in the second comment](https://github.com/Fabulously-Optimized/fabulously-optimized/issues/701#issuecomment-1676777005).

### Why did FO just not rename it?

At the time this change was made, Sodium had all strings hardcoded, so it would've been impossible anyway. Admittedly, [that changed in only 15 days later](https://github.com/CaffeineMC/sodium-fabric/commit/5306c9c382b6a296f6b6b3db50ca9859b9519423), but at the time I was not aware of that change either. 

Either way, FO did not contain any bundled resource packs until [after two months.](https://github.com/Fabulously-Optimized/fabulously-optimized/blob/main/CHANGELOG.md#220-2021-09-29)

### Why did FO not discuss the issue with Sodium at the time? Why did FO not rename it later?

Because it was not seen as an issue until now. 

Most mods do not have such donation buttons, so users who want to donate to them would need to refer to their listing pages anyway, and FO has Mod Menu for that.
The idea was that mod authors get their fair share through the modding platforms FO is in, and as described in the rant above, I do what I can to ensure every mod _is_ treated fairly and gets its share, by recommending launchers that allow it, using manifest values/direct download URLs to increase their download count etc.

### After the issue was brought up, why did FO not change it immediately?

As mentioned [in the second comment](https://github.com/Fabulously-Optimized/fabulously-optimized/issues/701#issuecomment-1676777005), the original issue still remains to this day, and is not exclusive to this modpack. 

Nonetheless, I discussed the issue with JellySquid and proposed fixes: [one simpler fix that could be done right now](https://github.com/CaffeineMC/sodium-fabric/pull/2008) in upstream (but has not been agreed upon yet) and [one that Jelly agreed upon](https://discord.com/channels/602796788608401408/651120262129123330/1140670877839667240), but is a bigger change and takes more time to implement.

### What is the status of this in FO now?

As of [FO 5.3.0-beta.3](https://github.com/Fabulously-Optimized/fabulously-optimized/blob/main/CHANGELOG.md#530-beta3-2023-08-20)/[Sodium 0.5.2](https://github.com/CaffeineMC/sodium-fabric/releases/tag/mc1.20.1-0.5.2), users [can see the donation links in Mod Menu](https://github.com/CaffeineMC/sodium-fabric/commit/9170dadf98f4c2638e4c80e7b3ceb48a343542ac).

However, _this issue specifically_ has still been lingering, so to resolve it, I've now decided to work around it on the FO side. 
The donation button has been re-enabled in the latest versions and the text has been changed to "Support Sodium!", a phrasing that was favored by 4 Sodium users at the time.

### What's FO's stance on donation-related features overall?

Donation buttons contained in individual mod settings are okay. In Sodium's case the "mod settings" is just _the video settings_ page and as such, the wording should be very clear on who gets the donation. 

However, other kinds of donation features like colored names, "glow", capes etc for specific mods that _were not_ created for providing cosmetics are considered unwanted and will be disabled in FO. As of 5.2.8/5.3.0-beta.6, no mods in FO provide such features.

**Comment by Madis0** [comment]
As of Sodium 0.5.6, it is no longer possible to independently and reliably toggle this button, so as of Fabulously Optimized 5.8.0-beta.7, it has been disabled, with the following (temporary?) workaround applied:

![pilt](https://github.com/Fabulously-Optimized/fabulously-optimized/assets/8611110/3f3f5c7e-dd3e-43f3-b89e-75593eaad687)

Unfortunately, the workaround is not clickable, hence the full URL is displayed. To resolve this, an issue has been made on Sodium's repo: https://github.com/CaffeineMC/sodium-fabric/issues/2293

**Comment by Madis0** [comment]
As of 5.8.0-beta.8, the workaround has been reverted, the button and the prompt have been re-enabled.
