### ISSUE TITLE
Start-up animation delay

### ISSUE THREAD

**Issue by Tiagoquix** [Fabulously-Optimized/fabulously-optimized#773]
### What config to change

According to the 5.6.0 (latest update for the modpack), FO now has a previously-non-existent 0.5 seconds delay for the splash screen.

> The startup animation splash is now set to 0.5 seconds (compared to vanilla 2 seconds, previous FO version 0 seconds)
>> The value can be adjusted in Remove Reloading Screen settings

It should be changed back to zero seconds.

### Why should it be changed

I see no reason to keep an artificial delay of 0.5 seconds for the splash screen.

It doesn't matter the context: the less delay it takes to load, the better.

**Comment by Madis0** [comment]
The change was done to find a balanced solution that would satisfy the 59% who voted for Fadeless keeping and 41% for removal at #737. So instead of removing the animation entirely, I made it 4x faster than vanilla and configurable.

I can still consider tweaking the value even faster or adjusting other settings of RRLS, but at this point I don't think setting it to 0 seconds is a good solution.

**Comment by Madis0** [comment]
I encourage you to join our Discord and read the full conversation of the "Remove Fadeless" thread to get the full context on why this change was made and what other alternatives were proposed.

**Comment by Madis0** [comment]
Decided that the current value of 0.5s is still a good balance of "improved speed" vs "being jarring". This matches the previously ran public survey of FO users' benefits.

Luckily, the value is also easy to change for those who prefer 0s, 2s or something else - `Mods`, search "Remove Reloading Screen", 🎛️, adjust the slider, save.
