### ISSUE TITLE
Enchantment glint missing

### ISSUE THREAD

**Issue by Skitty22** [Fabulously-Optimized/fabulously-optimized#782]
### Describe the bug

Enchantment glints dont seem to work. Its like they are invisible. I use shaders and thought that was the problem. I turned those off and still nothing. I use vanilla resources packs so it isnt anything to do with that either. I change the enchantment glint to 100% in accessibility settings and still nothing not even a slight haze of enchantment glints. Im not really sure if anyone else has had this issue or if it's a mod issue with this pack. But I cant seem to find anything on it or a solution.

### Modpack version

5 4.4

### Launcher

MultiMC

### Confirm

- [X] This bug report is about an issue with the modpack itself, I have not modified the mods nor added any resource packs. If this is not the case, I know that I should post the issue to modpack's Discord support channel instead.

**Comment by Madis0** [comment]
Please update to the latest stable version (5.6.3) and retry.

**Comment by Madis0** [comment]
No response and cannot reproduce myself. 

Keep in mind the enchantment glint [is more subtle since 1.19.4](https://minecraft.wiki/w/Java_Edition_1.19.4#General_2), so you may want to try [resource packs like this to make it more visible again](https://modrinth.com/resourcepack/chromaglint/gallery).
