### ISSUE TITLE
Faster Random

### ISSUE THREAD

**Issue by nyabinary** [Fabulously-Optimized/fabulously-optimized#873]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/faster-random

### CurseForge Mod Distribution

Not allowed

### Modrinth link

https://modrinth.com/mod/faster-random

### Source/other link

https://github.com/AnOpenSauceDev/FastRandom

### Mod file size

20.21 KB

### License

(any other license)

### What it does

Rewrites Minecraft's RNG system with a newer and much faster alternative, making random operations up to 100X* faster, and makes parts of minecraft load faster in some cases.

* In the worst-case-scenario with CheckedRandom. Realistically performance on most operations are 4-8x faster.

### Why should it be in the modpack

Near vanilla parity, with only some cave shapes being _slightly_ different. Also fixes this bug, which is a nice bonus (on top of the faster performance) https://bugs.mojang.com/browse/MC-239059

### Why shouldn't it be in the modpack

Mod distribution as well as it not being 100% vanilla parity yet, also mileage may vary depending on hardware.

### Additional details

Faster Random performs better alongside other terrain optimization mods such as Noisium(#760) and C2ME(#39)

**Comment by AnOpenSauceDev** [comment]
_ehh_, I'm not sure if Faster Random should be placed in a pack that's downloaded by unassuming people. With mods that add structures, biomes and such, then that would make sense to me as parity has been thrown out of the window due to the shuffling.

Possibly adding a toggle to enable Faster Random for a world might be useful (it would just tag a world if it was generated with it and let you restart with the mod off however), because having it enabled for all worlds will lead to people getting confused when looking at certain seeds that have interesting cave generation, only to see something a bit different.

It's really up to what the community deems as "good enough". This isn't a fully 1:1 thing like Noisium.

**Comment by nyabinary** [comment]
> _ehh_, I'm not sure if Faster Random should be placed in a pack that's downloaded by unassuming people. With mods that add structures, biomes and such, then that would make sense to me as parity has been thrown out of the window due to the shuffling.
> 
> Possibly adding a toggle to enable Faster Random for a world might be useful (it would just tag a world if it was generated with it and let you restart with the mod off however), because having it enabled for all worlds will lead to people getting confused when looking at certain seeds that have interesting cave generation, only to see something a bit different.
> 
> It's really up to what the community deems as "good enough". This isn't a fully 1:1 thing like Noisium.

It's like 99% parity though isn't it and OptiFine world generation is way more screwed up right?

**Comment by AnOpenSauceDev** [comment]
I don't think so by default, but the built-in Fast Math (which optimizes worldgen, movement, etc) affects almost everything, which lead to some drama due to it technically being a semi unfair advantage in parkour.

**Comment by Madis0** [comment]
Unfortunately _near vanilla_ worldgen is not _vanilla_, and as such this is not suitable for this modpack. Hopefully Mojang will improve the performance on their own.
